package.json
release-notes.md
src/NeoDash.js
src/card/report/NeoMapReport.js
src/component/NeoSaveLoadModal.js
src/component/NeoShareModal.js
src/component/NeoTextButton.js
src/index.js

- Added dashboard sharing functionality.
- Fixed unintuitive margins for bar chart reports.
- Added abort button to save/load screen.
- Added automatic fix for inconsistent DB url + encryption configurations.

Release 1.1.1

---

README.md
tools/neodash-build-run.bash
tools/neodash-build-run_unix.bash
tools/neodash-build-run_windows.bash

I've update in tools the docker launch script adding a way to run the image both on Windows and Linux. Also I've added an option to specify the port where Neo4Dash will be served. 
It's not grand, but I hope it'll be useful.

Refactoring docker script

---

src/card/view/CardView.tsx

Disable refresh when a global parameter is changed that is not used in the report

Report updates base on global params

---

Dockerfile
README.md
package.json
release-notes.md
scripts/config-entrypoint.sh
scripts/message-entrypoint.sh
scripts/push-docker-image.bash
src/application/Application.tsx
src/application/ApplicationThunks.ts
src/card/view/CardView.tsx
src/card/view/CardViewFooter.tsx
src/card/view/CardViewHeader.tsx
src/chart/IFrameChart.tsx
src/chart/MarkdownChart.tsx
src/chart/TableChart.tsx
src/chart/util/ChartUtils.ts
src/config/DashboardConfig.ts
src/config/ReportConfig.tsx
src/dashboard/Dashboard.tsx
src/dashboard/header/DashboardHeader.tsx
src/modal/AboutModal.tsx
src/settings/SettingsThunks.ts

This is the final minor update before the 2.1 release.
Updates:
- Updated Dockerfile to make better use of caching, and pick up environment variables at run time.
- Added option to replace dashboard parameters in Markdown/iFrames to make them dynamic.
- Removed unneeded index column from the CSV download for tables.
- Added optional dashboard setting to enable image downloads for reports/the entire dashboard.

2.0.15 Release

---

docs/modules/ROOT/pages/user-guide/reports/single-value.adoc
src/card/view/CardView.tsx
src/config/ReportConfig.tsx

Hi Niels,
Here's my first attempt to contribute to this great project.
I've simply added backgroundColor to singleValue cardView.
Card with color:
Settings

Add bg color

---

src/card/settings/custom/CardSettingsContentPropertySelect.tsx

node property parameter-select: order results by size ASC

---

.github/workflows/master-deployment.yml
Dockerfile
changelog.md
package.json
release-notes.history.md
release-notes.md
src/chart/MapChart.tsx
src/modal/AboutModal.tsx

Added hotfix for broken map visualization (#184)

2.1.4 Release

---

src/chart/visualizations/SankeyVisualization.tsx
src/chart/visualizations/Utils.ts

Solving https://github.com/neo4j-labs/neodash/issues/203

Cycle detection

---

.github/workflows/master-deployment.yml

Hotfix for master deployment script

---

.github/workflows/master-deployment.yml
Dockerfile
changelog.md
package.json
release-notes.md
src/application/ApplicationActions.ts
src/application/ApplicationReducer.ts
src/application/ApplicationSelectors.ts
src/application/ApplicationThunks.ts
src/card/Card.tsx
src/dashboard/Dashboard.tsx
src/modal/AboutModal.tsx
src/report/Report.tsx
src/settings/SettingsSelectors.ts

Also:
- added a security warning in the case that people run the app with a plaintext password.
- Cleaned up some unused old variables from Report.tsx.

Added hotfix for race condition in Neo4j Desktop

---

.github/workflows/master-deployment.yml
Dockerfile
changelog.md
package.json
release-notes.md
src/application/ApplicationActions.ts
src/application/ApplicationReducer.ts
src/application/ApplicationSelectors.ts
src/application/ApplicationThunks.ts
src/card/Card.tsx
src/dashboard/Dashboard.tsx
src/modal/AboutModal.tsx
src/report/Report.tsx
src/settings/SettingsSelectors.ts

* Added hotfix for race condition in Neo4j Desktop
* Bumped version number
* Added check to ensure the database list doesn't get reloaded too often
* Added TODOs

2.1.9 Release

---

docs/modules/ROOT/pages/user-guide/reports/bar-chart.adoc
src/chart/bar/BarChart.tsx
src/config/ReportConfig.tsx

There's an eventual option on creating custom bars from here

Custom label position

---

gallery/src/App.tsx

By request of one of the contributors.

Updated gallery to allow for logos to be put in the card header

---

docs/modules/ROOT/pages/user-guide/reports/line-chart.adoc
src/chart/line/LineChart.tsx
src/config/ReportConfig.tsx

Fix regression on date/datetimes after Record Mapper prune.

Closes #243 line graph with datetime crashing

---

gallery/package.json
gallery/setup.md
gallery/src/App.tsx

and added instructions on how to re-build the setup.

Fixed gallery to point to new read-only database

---

src/chart/parameter/component/NodePropertyParameterSelect.tsx

This resolves https://github.com/neo4j-labs/neodash/issues/338

Passed all dashboard parameters to populating query for selector

---

docs/modules/ROOT/pages/user-guide/reports/line-chart.adoc
src/chart/line/LineChart.tsx
src/config/ReportConfig.tsx

Solve #323 
Add advanced setting to line charts to turn it into a scatter plot

Scatter plot

---

.husky/common.sh
.husky/pre-commit

Hey, the goal of this fix is the solve the issue #342, according to the official Husky doc https://typicode.github.io/husky/#/?id=yarn-on-windows

Fix husky Windows issue

---

gallery/yarn.lock
src/application/Application.tsx

The pain to find the cause was real 😢 but totally worth it 
With this PR, HMR should work as expected again
https://user-images.githubusercontent.com/12672541/230106706-8d84e3fe-04e3-4029-bb42-37091249a062.mp4

fix: hmr with webpack

---

src/card/view/CardView.tsx
src/card/view/CardViewFooter.tsx
src/chart/graph/GraphChart.tsx
src/chart/graph/util/RecordUtils.ts

Fix and Chips

---

docs/modules/ROOT/pages/user-guide/reports/sankey.adoc
src/extensions/advancedcharts/chart/sankey/SankeyChart.tsx

Forcing value to 1 on SANKEY_UNWEIGHTED property value

Unweighted Sankey Charts

---

src/chart/ChartUtils.ts
src/config/ReportConfig.tsx

Urls params weren't properly parsed by RenderSubValue

Fix on replace rules

---

public/style.css
src/application/Application.tsx
src/card/view/CardView.tsx
src/component/theme/Themes.tsx
src/config/DashboardConfig.ts

Luma limit is set on 40, not sure if we want this to be a dashboardSetting.

Header color on dark background

---

src/chart/map/layers/MarkerLayer.tsx

Fix render on map for this repo

Fix render on map

---

.github/workflows/develop-deployment.yml
.github/workflows/develop-test.yml
.github/workflows/master-deployment.yml
.github/workflows/master-test.yml

Aligned whitespaces, fix issue with old Cypress version being used by some of the actions.

Clean up Github actions

---

package.json
src/index.tsx
yarn.lock

Adding error monitoring for public/test environments.
CC @jexp

Add sentry.io

---

src/card/Card.tsx
src/extensions/actions/ActionsRuleCreationModal.tsx
src/extensions/styling/StyleRuleCreationModal.tsx

Replaced fixed widths and bad <td> to use percentage widths for better responsive control

Remove fixed widths in report actions modal

---

.github/workflows/master-deployment.yml
Dockerfile
changelog.md
docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc
package.json
release-notes.md
src/modal/AboutModal.tsx

What's new in NeoDash 2.3.2? A few bug fixes, performance improvements and more important, it ships phase 2 of our migration to [Needle](https://neo4j.com/developer-blog/needle-neo4j-design-system/)  !
- Key Features:
- UI updated to use the **[Neo4j Design Language](https://www.neo4j.design/)** phase 2, giving NeoDash a similar look-and-feel to other Neo4j tools. This includes the removal of the sidebar and a complete refactor on the header component. ([@mariusconjeaud](https://github.com/mariusconjeaud),[@konsalex](https://github.com/konsalex),[@BennuFire](https://github.com/bennufire), [#552](https://github.com/neo4j-labs/neodash/pull/552))
- *Experimental* Support for **Dark Mode**. 
- Parameter Selector Chart
- New advanced setting 'Manual Parameter Save' allowing  dashboard …

Add release notes 2.3.2

---

src/chart/table/TableChart.tsx

Fix https://github.com/neo4j-labs/neodash/issues/595

Multiple rules on tables

---

src/chart/graph/component/GraphChartInspectModal.tsx
src/chart/graph/util/NodeUtils.ts

Based on https://github.com/neo4j-labs/neodash/pull/592/commits/2d09aae1254b37d6c99dfab80febe7b28b23b05f shared via https://github.com/neo4j-labs/neodash/pull/592
Thanks to @brahmprakashMishra

Vulcan 231 source target

---

public/index.html
public/style.css
src/card/settings/CardSettingsContent.tsx
src/card/view/CardViewFooter.tsx
src/chart/bar/BarChart.tsx

Also a fix for the dropdowns on fullscreen

Fix Bar Colors assignment

---

src/chart/ChartUtils.ts
src/chart/parameter/component/NodePropertyParameterSelect.tsx
src/report/ReportRecordProcessing.tsx

Fixes https://github.com/neo4j-labs/neodash/issues/563

Fix number display 

---

src/extensions/query-translator/clients/const.ts
src/index.tsx
webpack.config.js

Sentry init only on http://neodash.graphapp.io/

Sentry on served

---

.github/workflows/master-deployment.yml
Dockerfile
cypress/e2e/start_page.cy.js
package.json
src/chart/table/TableChart.tsx
src/extensions/forms/chart/NeoForm.tsx

Fixing missing capability to hide a column from the query by adding the prefix __.

Fix hiding column prefix

---

src/chart/graph/component/GraphChartEditModal.tsx
src/dashboard/sidebar/DashboardSidebar.tsx
src/extensions/forms/chart/NeoForm.tsx
src/extensions/query-translator/component/OverrideCardQueryEditor.tsx

Hello, I'm taking a software quality course, and as a final assignment, we were instructed to perform code smell refactorings in open source projects. For this issue I identified the Enum Implicit Value smell in 7 components.
The Enum Implicit Value occurs when an enumeration has no explicit numerical values for each of its variants. This can lead to bugs when the enum values are used in a numerical situation and new variants are introduced, since the typescript compiler will assign an automatic value for each variant.
Code quality metrics were collected with Understand, before and after refactoring, but for this code smell, there was no change.
| AvgCyclomatic | CountDeclFunction | Cyclomatic | SumCyclomatic | MaxNesting | CountLine | CountLineComment |
| --- | --- | --- | --- | --- | …

Refactor enum implicit values code smells

---

src/card/settings/CardSettingsFooter.tsx
src/card/view/CardView.tsx
src/chart/bar/BarChart.tsx
src/chart/graph/GraphChart.tsx
src/chart/graph/GraphChartVisualization2D.tsx
src/chart/scatter/ScatterPlotChart.tsx

Hello, I'm taking a software quality course, and as a final assignment, we were instructed to perform code smell refactorings in open source projects. For this issue, I identified the Any Type smell 8 times in the project.
The Any Type smell occurs when a proper type is not provided in a context, or the "any" keyword is explicitly used. It's recommended to use a real type when possible, or prefer the "unknown" keyword instead of "any".
Code quality metrics were collected with Understand, before and after refactoring, and for this code smell, only the CountLine was affected:
| AvgCyclomatic | CountDeclFunction | Cyclomatic | SumCyclomatic | MaxNesting | CountLine | CountLineComment |
| --- | --- | --- | --- | --- | --- | --- |
| 1,93 | 1933 | 3272 | 9594 | 14 | 57043 | 3413|
This pull …

Refactor any type code smells

---

src/chart/table/TableChart.tsx
src/dashboard/header/DashboardTitle.tsx
src/extensions/ExtensionsModal.tsx
src/extensions/text2cypher/component/QueryTranslatorButton.tsx
src/modal/ExportModal.tsx
src/settings/SettingsModal.tsx

Small fixes to styling and improved usability through tooltips & reduced nesting

Improved styling of dashboard header buttons, download CSV button

---

src/chart/parameter/component/NodePropertyParameterSelect.tsx
src/config/ReportConfig.tsx

Replacement for https://github.com/neo4j-labs/neodash/pull/736/

Added parameter select setting for autopopulating first selector value

---

.github/workflows/master-deployment.yml
Dockerfile
changelog.md
docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc
package.json
release-notes.md
src/modal/AboutModal.tsx

Adding in release notes and bumping version to 2.4.2.

2.4.2 Release Notes

---

src/application/ApplicationReducer.ts

Add 'UPDATE_SELECTION' as one of the cases where it should not be marked as draft.

Fixed issue where dashboards were marked as draft incorrectly on selection change

---

docs/modules/ROOT/pages/developer-guide/configuration.adoc

Update Configuration Docs

---

src/chart/ChartUtils.ts

added prefix in the exported file to force utf-8 encoding

adding symbol to force utf-8 casting in Excel

---

cypress/e2e/bar_chart.cy.js
cypress/e2e/start_page.cy.js

Causing issues in the CI pipeline

Temporarily disabled flaky Cypress tests

---

src/chart/parameter/component/DateParameterSelect.tsx
src/extensions/advancedcharts/chart/gauge/GaugeChart.tsx
src/extensions/advancedcharts/chart/radar/RadarChart.tsx
src/extensions/advancedcharts/chart/sankey/SankeyChart.tsx

Reverts neo4j-labs/neodash#806

Revert "Fix Radar number NaN High-Low"

---

package.json
src/application/ApplicationActions.ts
src/application/ApplicationReducer.ts
src/application/ApplicationThunks.ts
src/component/sso/SSOUtils.ts
src/dashboard/Dashboard.tsx
yarn.lock

Reverts neo4j-labs/neodash#611

Revert "Handle token expiration in SSO"

---

src/chart/parameter/ParameterSelectionChart.tsx
src/chart/parameter/component/NodePropertyParameterSelect.tsx
src/chart/parameter/component/ParameterSelect.ts
src/chart/parameter/component/QueryParameterSelect.tsx

#856 Disable auto-sorting of Cypher query Parameter Select

---

src/extensions/rbac/RBACManagementMenu.tsx
src/extensions/rbac/RBACUtils.ts

This feature update does 2 things:
1. Makes role selector scrollable
2. Makes user update more robust to handle < tokens, @ etc in their name

Update role selector menu + more robust user updates

---

src/config/ReportConfig.tsx

Signed off: Monish [monish.nandakumaran@mercedes-benz.com](mailto:monish.nandakumaran@mercedes-benz.com)

fix: in report config bar chart removed duplicate settings

---

.github/workflows/master-deployment.yml
Dockerfile
changelog.md
docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc
docs/modules/ROOT/pages/developer-guide/style-configuration.adoc
package.json
release-notes.md
scripts/config-entrypoint.sh
src/application/ApplicationActions.ts
src/application/ApplicationThunks.ts
src/chart/table/TableChart.tsx
src/config/ReportConfig.tsx
src/extensions/forms/FormsReportConfig.tsx
src/extensions/forms/chart/NeoForm.tsx
src/extensions/forms/settings/NeoFormCardSettingsModal.tsx
src/extensions/rbac/RBACManagementMenu.tsx
src/extensions/rbac/RBACManagementModal.tsx
src/extensions/rbac/RBACUtils.ts
src/modal/AboutModal.tsx
src/modal/ExportModal.tsx
src/report/ReportQueryRunner.ts
src/report/ReportRecordProcessing.tsx

This is a minor release containing a few critical fixes and general code quality improvements:
- Fix multiple parameter select ([881](https://github.com/neo4j-labs/neodash/pull/881)).
- Fix parameter casting error when loading dashboards([874](https://github.com/neo4j-labs/neodash/pull/874)).
- Fix the fraud demo in the [Example Gallery](https://neodash-gallery.graphapp.io/).

Release notes for release 2.4.7

---

src/chart/graph/util/RecordUtils.ts

Fixes https://github.com/neo4j-labs/neodash/issues/879

Fix: Default rel width applied on missing property value

---

docs/modules/ROOT/pages/developer-guide/build-and-run.adoc
k8s-deploy/neodash/.helmignore
k8s-deploy/neodash/Chart.yaml
k8s-deploy/neodash/README.md
k8s-deploy/neodash/templates/NOTES.txt
k8s-deploy/neodash/templates/_helpers.tpl
k8s-deploy/neodash/templates/deployment.yaml
k8s-deploy/neodash/templates/hpa.yaml
k8s-deploy/neodash/templates/ingress.yaml
k8s-deploy/neodash/templates/service.yaml
k8s-deploy/neodash/templates/serviceaccount.yaml
k8s-deploy/neodash/templates/tests/test-connection.yaml
k8s-deploy/neodash/values.yaml
k8s-deploy/sample-k8s-yamls/deployment.yaml
k8s-deploy/sample-k8s-yamls/service.yaml

Had to create a new PR for the review + small changes since the initial PR was on an external fork
For reference: #902 
Changes:
- Code review
- Small typo
- Documentation

[Feature #884] Helm chart for Kubernetes deployments PR#902

---

docs/modules/ROOT/pages/user-guide/faq.adoc

Edited section of the FAQ on supportability.

Patch FAQ on supportability
