.env.hosted, README.md, doc/developer-guide.md, package.json, public/style.css, release-notes.md, src/NeoDash.js, src/card/NeoCard.js, src/card/NeoCardSettings.js, src/card/report/NeoMarkdownReport.js, src/card/report/experimental/NeoBigNumberReport.js, src/card/report/experimental/NeoLiveTimeChartReport.js, src/card/report/experimental/NeoSearchBarReport.js, src/component/NeoShareModal.js, src/index.js
- Changed base URL to https://neodash.graphapp.io
- Resolved bug that didn't allow for connecting to a remote DBMS without encryption
- Added customizable background color for dashboards using "background" Cypher parameter
- Added option to hide table footers using "hideFooter" Cypher parameter
- First experimental reports added
=> Release 1.1.2

package.json
First of all, thank you for developing Neodash! I think it will prove to be very useful for us (I work with @bartbroere).
This PR fixes the `build` commands on MacOS. The `cp` command on macOS (at least in Monterey using the default zsh shell) requires the `-r` flag to be supplied _before_ the source and target, not after.
=> Fix Neodash 2 build commands on macOS

public/index.html
The path to the compiled Javascript file was wrong: it tries to go up a directory when it shouldn't. Amazingly the current version still works if you host directly from the `dist` folder I guess because there is no dir to go up to?
Anyway, this should make it work in all cases.
=> Fix path to bundle.js

public/embed-test.html, src/chart/IFrameChart.tsx, src/chart/ParameterSelectionChart.tsx, src/config/ExampleConfig.tsx, src/config/ReportConfig.tsx, src/modal/DocumentationModal.tsx, src/report/Report.tsx
Copy paste the parameter select variable (e.g. `neodash_entity_name`) into the advanced settings of the iframe chart. Then see the magic happening via inspect element on the iframe. The hash value changes when you choose the value via parameter select chart, without re-rendering the iframe. Re-rendering iframe could be jarring and state could be lost, so it's important to ensure the chart doesn't re-render during these updates. Page within iframe can access value of `window.location.hash` and setup a listener to be notified of changes.
=> Pass Parameter Select value via hash to iframe without re-rendering

src/chart/GraphChart.tsx, src/config/ReportConfig.tsx, src/modal/GraphItemInspectModal.tsx, src/modal/GraphModal.tsx
Show modal when clicking node/relation in graph with its properties. This comes in handy when you want to copy/paste values from nodes displayed in the graph (the default tooltip disappears if you try to copy values from there). Also handy in case theres a URL in one of the properties. The URL will be clickable from the modal.
Perhaps not so great for dense graphs, as you may accidentally trigger the modal when dragging within the graph...
=> Graph modal

src/chart/TableChart.tsx, src/report/RecordProcessing.tsx
I reworked the way data types are handled in the Data Grid and added support for additional types: `boolean`, `number`, `date` and `datetime`. From the screenshot you can't really tell, but before all types were treated as strings. Which isn't great for filtering and sorting. Now you can filter properly with e.g. numeric comparison or filter cells before/after a certain date. In addition to that, `object` cells are now filterable. An `object` is transformed to a `string` with `JSON.stringify()`. But instead of doing that inside the `renderCell` function, I'm doing it with `valueGetter`, which happens before rendering and the output is used by the filtering and sorting functions. So you can now filter all objects containing the string `key` (which is all of them in this example xD).
You …
=> Support rendering native and custom types in Data Grid

README.md, tools/Dockerfile, tools/neodash-build-run.bash
I ended up cloning graph-chart from its fork, build it separately and rsync it to node_modules to get it work due to an issue discussed previously. Regardless, it builds and runs.
=> feat(docker): add Dockerfile, wrapper script to build & run

README.md
There is a small markdown typo which results in wrong rendering of the URL in the readme. Just a minor modification to fix that.
=> Fix URL to pre-built docker image in readme

src/chart/SingleValueChart.tsx, src/chart/TableChart.tsx, src/report/RecordProcessing.tsx
In a SingeValueChart, if the value can be parsed to an Integer, create a display value that contains whitespace thousand separators.
=> Add thousand separator for numbers, unified rendering for single number charts

package.json, release-notes.md, src/chart/MapChart.tsx, src/chart/ParameterSelectionChart.tsx, src/chart/visualizations/BarVisualization.tsx, src/config/ReportConfig.tsx, src/dashboard/DashboardDrawer.tsx, src/modal/AboutModal.tsx, src/modal/ConnectionModal.tsx, src/modal/DeletePageModal.tsx, src/modal/DocumentationModal.tsx, src/modal/GraphItemInspectModal.tsx, src/modal/LoadModal.tsx, src/modal/NotificationModal.tsx, src/modal/SaveModal.tsx, src/modal/ShareModal.tsx, src/modal/UpgradeOldDashboardModal.tsx, src/modal/WelcomeScreenModal.tsx, src/report/RecordProcessing.tsx, tools/Dockerfile
Stability fixes to supplement 2.0.7:
- Fix for rendering dictionaries in tables/single value charts.
- Added resize handler for fullscreen map views.
- Added missing auto-run config to pie charts.
- Fixed broken value scale parameter for bar charts.
=> Stability fixes for 2.0.11

public/config.json, src/application/ApplicationThunks.tsx
=> default password in config file

.github/workflows/master-deployment.yml, Dockerfile, changelog.md, package.json, release-notes.history.md, release-notes.md, src/chart/MapChart.tsx, src/modal/AboutModal.tsx
https://github.com/neo4j-labs/neodash/issues/183
=> Added Hotfix for broken map visualization

.github/workflows/develop-deployment.yml, .github/workflows/master-deployment.yml, Dockerfile, changelog.md, docs/modules/ROOT/pages/user-guide/dashboards.adoc, docs/modules/ROOT/pages/user-guide/reports/bar-chart.adoc, docs/modules/ROOT/pages/user-guide/reports/index.adoc, docs/modules/ROOT/pages/user-guide/reports/line-chart.adoc, gallery/src/App.tsx, package.json, release-notes.md, src/application/ApplicationActions.ts, src/application/ApplicationReducer.ts, src/application/ApplicationSelectors.ts, src/application/ApplicationThunks.ts, src/card/Card.tsx, src/chart/bar/BarChart.tsx, src/chart/line/LineChart.tsx, src/chart/pie/PieChart.tsx, src/config/ReportConfig.tsx, src/dashboard/Dashboard.tsx, src/modal/AboutModal.tsx, src/modal/ShareModal.tsx, src/report/Report.tsx, src/settings/SettingsActions.ts, src/settings/SettingsSelectors.ts, src/settings/SettingsThunks.ts
This is a minor update which adds some operational/styling improvements, and a bug fix for line charts.
Changes:
- Added customizable label positions for bar charts.
- Fixed bug where datetimes were not handled correctly by line charts. (https://github.com/neo4j-labs/neodash/issues/243)
- Added **session parameters**, set automatically and available to Cypher queries ([Documentation](https://neo4j.com/labs/neodash/2.1/user-guide/reports/)).
- Added option to restore debug reports in recovery mode.
- Added option to share dashboards from self-hosted deployments.
=> 2.1.10 Release

scripts/config-entrypoint.sh
Minor fix in [scripts/config-entrypoint.sh](https://github.com/neo4j-labs/neodash/pull/269/files#diff-3280c776a7f48c1df84537f1530854e2c1b21b4f14d38dad8d78baabe1a4da3f) that adds standaloneDashboardURL to /usr/share/nginx/html/config.json.
This is to fix Issue #160
=> Fixes #160

package.json, yarn.lock
Fixes a bug in the syntax highlighting where the decorations weren't being cleared, which apparently can cause a crash when the text value changes rapidly
=> Bump @neo4j-cypher/react-codemirror to pre 18

package.json, yarn.lock
Sorry for the churn right after a previous PR to bump the editor version, but there's now a new editor release that fixes a potential serious bug where minifying the editor source code could break the parser logic.
This bug doesn't affect neodash currently, but it very easily could if you change/update the build tools such as webpack.
=> update editor for minification bugfix (constructor.name)

.github/workflows/master-deployment.yml, Dockerfile, changelog.md, docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc, docs/modules/ROOT/pages/user-guide/reports/map.adoc, package.json, release-notes.md, src/card/settings/custom/CardSettingsContentPropertySelect.tsx, src/modal/AboutModal.tsx
This releases fixes a small set of bugs that slipped through the 2.2.3 release, and adds some minor features:
- Added support for scatter plots by overriding a parameter in the line chart.
- Added the ability to use dashboard parameter as filters in custom parameter selector queries.
- Fixed breaking bug in parameter selector settings causing a white-screen error.
- Fixed auto-coloring of bar charts (resolved back to logic of 2.2.1 and earlier).
- Upversioned outdated dashboards and in the NeoDash Gallery.
=> Added release notes for 2.2.3

package.json, src/component/editor/CodeEditorComponent.tsx, yarn.lock
We officially released the new cypher editor today, so this PR reflects that.
I hit an interesting issue with `yarn` where the following caused issues:
```
edit package.json to use "@neo4j-cypher/react-codemirror": "^1.0.0"
yarn install
```
The resulting lock file had two copies of a bunch of packages including "@codemirror/state". This broke things, and the only way I could fix it was to delete the `yarn.lock` file and re-create it from scratch :-/.
It seems that newer versions of yarn (> 1.x) automatically de-dupe packages during install so it might be worth it to think of upgrading yarn...
=> New Cypher Editor 1.0.0 now released

.github/workflows/master-deployment.yml
The docker image for 2.3.0 was only published to `nielsdejong/neodash` (legacy) and not `neo4jlabs/neodash`.
This PR fixes that issue.
=> Fixed invalid secret being used to publish docker image

src/application/ApplicationThunks.ts
Both the port number and protocol were not set correctly when creating a share link without credentials.
This PR fixes that issue.
=> Passing protocol and port through share links correctly

src/card/settings/CardSettings.tsx, src/card/settings/CardSettingsContent.tsx, src/card/view/CardView.tsx, src/card/view/CardViewHeader.tsx, src/chart/parameter/ParameterSelectionChart.tsx, src/component/editor/CodeViewerComponent.tsx, src/dashboard/header/DashboardHeader.tsx, src/dashboard/header/DashboardTitle.tsx, src/extensions/ExtensionsModal.tsx, src/extensions/actions/ActionsRuleCreationModal.tsx, src/extensions/styling/StyleRuleCreationModal.tsx, src/report/Report.tsx
While testing out 2.3.2, found some places where we can improve contract between lines/borders/background to make the UI a bit nicer.
Also did some Needle styling fixes on the actions / rule-based styling modals.
=> Improved contrast for light and dark theme interfaces

src/application/ApplicationThunks.ts
**Problem**
Neodash frontend will be served from subpath. eg., https://mercedes-benz.com/neodash/ui/. So in shared dashboard after loading the credentials the page reloads and subpaths are gone. Because of this logo and favicon is not loaded in UI.
**Solution**
Replaced the path with window.location.pathname
**NOTICE:**
The program was tested solely for our own use cases, which might differ from yours.
Author Info: Monish [monish.nandakumaran@mercedes-benz.com](mailto:monish.nandakumaran@mercedes-benz.com) on behalf of Mercedes-Benz Research and Development India
[https://github.com/mercedes-benz/mercedes-benz-foss/blob/master/PROVIDER_INFORMATION.md](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
=> Replace hardcoded subpath with window.location.pathname

public/style.css
Table's filter tooltip have been displaced on the top of table instead of over the first filtered result to allow users evaluate the result.
Before:
After:
=> Change on filter tooltip to avoid hide table data (Hotfix for #629)

src/chart/parameter/ParameterSelectCardSettings.tsx, src/dashboard/header/DashboardHeaderAboutButton.tsx, src/dashboard/header/DashboardHeaderPageTitle.tsx, src/dashboard/header/DashboardTitle.tsx, src/extensions/advancedcharts/chart/gantt/frappe/GanttVisualization.tsx
Hello, I'm taking a software quality course, and as a final assignment, we were instructed to perform code smell refactorings in open source projects. For this issue, I identified the Missing Union Type smell in 5 components.
The Missing Union Type occurs when a union type is used inline, without a proper type alias definition. It's recommended to have a type alias, improving maintainability and reducing possible code repetition.
Code quality metrics were collected with Understand, before and after refactoring, and for this code smell, only the CountLine was affected:
| AvgCyclomatic | CountDeclFunction | Cyclomatic | SumCyclomatic | MaxNesting | CountLine | CountLineComment |
| --- | --- | --- | --- | --- | --- | --- |
| 1,93 | 1933 | 3272 | 9594 | 14 | 57053 | 3413|
This pull request …
=> Refactor missing union type code smells

src/dashboard/sidebar/modal/DashboardSidebarImportModal.tsx
Hello, I'm taking a software quality course, and as a final assignment, we were instructed to perform code smell refactorings in open source projects. For this issue, I identified the Uncontrolled Component smell in 1 component.
The Uncontrolled Component smell occurs when a form doesn't use a state or prop, leading the form handling to the DOM itself. Sometimes this mean using a "ref" to access the input value instead of a state.
Code quality metrics were collected with Understand, before and after refactoring, and for this code smell, the cyclomatic, cyclomatic sum, number of functions and count line metrics were affected:
| AvgCyclomatic | CountDeclFunction | Cyclomatic | SumCyclomatic | MaxNesting | CountLine | CountLineComment |
| --- | --- | --- | --- | --- | --- | --- |
| 1,93 | …
=> Refactor uncontrolled component code smells

src/chart/parameter/ParameterSelectCardSettings.tsx
Partial fix for https://github.com/neo4j-labs/neodash/issues/686
=> Ordering suggestion values by length in parameter selector report

src/dashboard/DashboardThunks.ts
Fix: when loading a dashboard cast the javascript object (parsed from JSON) back to a Neo4jDate.
=> Fix race condition caused by incorrect date casted from serialized dashboard format

src/extensions/styling/StyleRuleEvaluator.ts
There was a double casting at number in the code preventing the correct application of the rule
=> fixing rule based styling wrong casting at number

src/chart/graph/GraphChart.tsx, src/dashboard/header/DashboardHeaderPageTitle.tsx, src/dashboard/header/DashboardTitle.tsx
Made the following changes to improve the UX:
- Dashboard titles are auto-saved when a user types a character (debounced)
- Editing mode for an input mode is automatically disabled if the user hits enter, or switches focus in the page.
- Input boxes now adjust to the width of the text.
- Styling of the text inside the input box is now closer to the style of the 'read' version, preserving logical context.
Bonus feature: added a small workaround for overriding default styling for graph visualizations in dark mode.
=> Improved UX for editing page headers & dashboard title

scripts/config-entrypoint.sh
I have added the option to configure **standalonePasswordWarningHidden** property of **config.json** using docker environment variables. Without this is not possible to set this propoerty to True in order to hide the warning message.
Just added this new property to config-entrypoint.sh to set this property in config.json. False by default.
If necessary, I will update the documentation to reflect this new configuration option. Please let me know if this is required.
=> Fix - Added standalonePasswordWarningHidden option to config-entrypoint.sh

src/extensions/actions/ActionsRuleCreationModal.tsx, src/extensions/advancedcharts/Utils.ts
Drafting solution, looks  like is deeper than expected in the graphChart
Still missing:
1. can't apply rule to links
2. to understand why the code is breaking from the graphChart (ruleValues arrive in the form (label.rValue)
=> Fixing wrong behaviour in GraphChart report Action

src/chart/ChartUtils.ts
parsing function toNumber was lacking of the base condition of checking if the value was already a number
=> fixing number parsing

src/extensions/forms/FormsReportConfig.tsx, src/extensions/forms/chart/NeoForm.tsx, src/extensions/forms/settings/NeoFormCardSettingsModal.tsx, src/extensions/rbac/RBACManagementMenu.tsx, src/extensions/rbac/RBACManagementModal.tsx, src/extensions/rbac/RBACUtils.ts, src/modal/ExportModal.tsx, src/report/ReportQueryRunner.ts
=> Fixing RBAC feature + parameters

package.json, src/chart/graph/component/GraphEntityInspectionTable.tsx, src/chart/table/TableChart.tsx, src/report/ReportRecordProcessing.tsx, yarn.lock
This includes rendering HTML strings in :
- Tables
- Inspector (Graph, Gantt)
Note that the HTML is sanitized before being rendered, thanks to the addition of DOMPurity. For example, this won't trigger an alert : `<b onmouseover='alert('mouseover');'>popup</b>`
=> #848 Render HTML strings

src/chart/ChartUtils.ts, src/chart/table/TableChart.tsx
This PR fixes a bug where passing a list as a report action would cause the output to be [object Object] for each element in that list.
The Cypher query returns the list object ['a', 'few', 'words'] as 'list'.
This is what previously happened when turning on a report action and its behaviour in other charts:
This is the result after the fix:
=> fixes bug where arrays are passed as [object Object]

src/chart/table/TableChart.tsx
Fixes some padding added to compact table rows when they contain report actions, making said rows not look compact.
=> Fix padding in compact table with report actions

src/chart/table/TableChart.tsx, src/config/ReportConfig.tsx
=> Make wrapping in table optional, enabled by default

src/application/ApplicationActions.ts, src/application/ApplicationThunks.ts
This PR makes sure we are correctly handling share links in all four scenarios where the dashboards database differs from the main "data" database:
- Link with credentials in read-only mode
- Link without credentials in read-only mode
- Link with credentials in editor mode
- Link without credentials in editor mode
=> Fixed issues where cross database dashboard sharing always reverted back to the default database

docs/modules/ROOT/pages/developer-guide/style-configuration.adoc, scripts/config-entrypoint.sh
Also updated the documentation (/developer-guide/style-configuration/) to describe how to use the environment variables for overriding style configuration.
=> Added option to define style config using environment variables for the Docker image

.github/workflows/master-deployment.yml, Dockerfile, changelog.md, docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc, package.json, release-notes.md, src/modal/AboutModal.tsx
This is a minor release containing a few critical fixes and some extra style customizations:
- Fix bad text wrapping for arrays in tables ([868](https://github.com/neo4j-labs/neodash/pull/868)).
- Make wrapping in table optional, enabled by default ([872](https://github.com/neo4j-labs/neodash/pull/872)).
- Fixed issues where cross database dashboard sharing always reverted back to the default database ([873](https://github.com/neo4j-labs/neodash/pull/873)).
- Added option to define style config using environment variables for the Docker image ([876](https://github.com/neo4j-labs/neodash/pull/876)).
=> Added release notes for 2.4.6

.github/workflows/master-deployment.yml, Dockerfile, changelog.md, docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc, docs/modules/ROOT/pages/developer-guide/style-configuration.adoc, package.json, release-notes.md, scripts/config-entrypoint.sh, src/application/ApplicationActions.ts, src/application/ApplicationThunks.ts, src/chart/table/TableChart.tsx, src/config/ReportConfig.tsx, src/modal/AboutModal.tsx, src/report/ReportRecordProcessing.tsx
This is a minor release containing a few critical fixes and some extra style customizations:
- Fix bad text wrapping for arrays in tables ([868](https://github.com/neo4j-labs/neodash/pull/868)).
- Make wrapping in table optional, disabled by default ([872](https://github.com/neo4j-labs/neodash/pull/872)).
- Fixed issues where cross database dashboard sharing always reverted back to the default database ([873](https://github.com/neo4j-labs/neodash/pull/873)).
- Added option to define style config using environment variables for the Docker image ([876](https://github.com/neo4j-labs/neodash/pull/876)).
=> 2.4.6 Release

src/application/ApplicationThunks.ts, src/chart/ChartUtils.ts, src/dashboard/DashboardThunks.ts, src/extensions/advancedcharts/Utils.ts, src/settings/SettingsThunks.ts
When loading a dashboard, the parameters were always kept in the same format as the one stored in the state (EX: numbers with high,low should be casted to number)
=> fixing casting error at while loading the dashboards

cypress/e2e/render/array.cy.js, cypress/e2e/start_page.cy.js, cypress/e2e/utils.js, cypress/fixtures/cypher_queries.js, src/chart/table/TableChart.tsx, src/report/ReportRecordProcessing.tsx
#880 
Includes full Cypress tests for stuff related to the RenderArray method
=> Rendering of multiple parameter select

.github/workflows/master-deployment.yml, Dockerfile, changelog.md, docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc, gallery/dashboards/fraud.json, package.json, release-notes.md, src/chart/graph/util/RecordUtils.ts, src/modal/AboutModal.tsx, src/settings/SettingsThunks.ts
This is a minor release containing an important fix and other minor fixes:
- Fixed a bug where loading a dashboard would reset parameters to null ([887](https://github.com/neo4j-labs/neodash/pull/887)).
- Fix relationship width parameter for Graph report ([889](https://github.com/neo4j-labs/neodash/pull/889)).
Thanks to all the contributors for this release: 
- [alfredorubin96](https://github.com/alfredorubin96),
- [nielsdejong](https://github.com/nielsdejong).
=> 2.4.8 Release

src/application/ApplicationThunks.ts
Fixing edge case when sharing set standalone to True and authenticating using SSO led to a state when the standalone coming from then URLParams was overwritten by the config.json
=> adding param to manage SSO redirection

package.json, src/chart/markdown/MarkdownChart.tsx, src/index.pcss, yarn.lock
Fixes typo preventing rendering of tables and other plugin-based components ; adds sanitization ; adds styling for tables
Closes #836
=> Markdown tables not rendered #836

src/extensions/rbac/RBACManagementModal.tsx, src/extensions/rbac/RBACUtils.ts
Issue Resolved: Corrected the behavior when updating user permissions related to roles. Previously, deleting a user from a specific role inadvertently removed all users from that role. Additionally, adding a user to a role now properly retains the role for users who were previously assigned to it.
=> Current Users or ALL Users getting deleted in an Update

src/chart/ChartUtils.ts
Fixing issue linked to PR #951
=> Fix value.low existence check when value is not an Object

src/application/ApplicationThunks.ts, src/component/sso/SSOLoginButton.tsx
when redirecting we were losing context of the UrlParams defined by the user
=> fixing strange param behaviour with sso

docs/modules/ROOT/pages/index.adoc
line 1 already contains this reference, and the live docs have a duplicate entry
=> remove duplicate banner reference
